services:
  proxy_server:
    depends_on: 
      - backend 
      - front_web
    image: nginx:alpine
    container_name: proxy 
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot-etc:/etc/letsencrypt
    networks:
      - my_network

  front_web:
    build:
      context: ./front_web
      dockerfile: Dockerfile
    container_name: front_web
    restart: always
    environment:
      - PORT=3000
    expose:
      - "3000"
    networks:
      - my_network

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    networks:
      my_network:
        ipv4_address: 172.25.0.137

  certbot:
    depends_on:
      - proxy_server
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/usr/share/nginx/html -m pumpkinbee2001@gmail.com --agree-tos --no-eff-email --keep-until-expiring -d public-insight.co.kr -d www.public-insight.co.kr
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:  
  db_data:
  
